/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreferencesGUI.java
 *
 * Created on 20.10.2010, 18:58:47
 */

package com.inubit.research.textToProcess.gui;

import com.inubit.research.textToProcess.Constants;

import net.frapu.code.visualization.Configuration;

/**
 *
 * @author ff
 */
public class PreferencesGUI extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8991257616297883684L;
	private Configuration f_config = Configuration.getInstance();
	
    /** Creates new form PreferencesGUI */
    public PreferencesGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setPreferences();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        f_cbRemLowEnt = new javax.swing.JCheckBox();
        f_cbGenBBPools = new javax.swing.JCheckBox();
        f_cbGenDO = new javax.swing.JCheckBox();
        f_cbHighlightMeta = new javax.swing.JCheckBox();
        f_cbAddUnknown = new javax.swing.JCheckBox();
        f_cbIgnoreRelativeNPs = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        f_cbCreateMsgEvt = new javax.swing.JCheckBox();
        f_cbAddExtraCommLinks = new javax.swing.JCheckBox();
        f_bOK = new javax.swing.JButton();
        f_bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Model Generation"));

        f_cbRemLowEnt.setText("Remove nodes with low information content");

        f_cbGenBBPools.setText("Generate blackbox pools");

        f_cbGenDO.setText("Generate data objects");

        f_cbHighlightMeta.setText("Highlight meta-actor nodes");

        f_cbAddUnknown.setText("Add 'unknown' phrases to labels");

        f_cbIgnoreRelativeNPs.setText("Ignore relative clauses attached to NPs");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_cbGenBBPools)
                    .addComponent(f_cbGenDO)
                    .addComponent(f_cbAddUnknown)
                    .addComponent(f_cbRemLowEnt)
                    .addComponent(f_cbHighlightMeta)
                    .addComponent(f_cbIgnoreRelativeNPs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(f_cbGenBBPools)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_cbGenDO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_cbAddUnknown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_cbRemLowEnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_cbHighlightMeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_cbIgnoreRelativeNPs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lane Splitting"));

        f_cbCreateMsgEvt.setText("Always create message events");

        f_cbAddExtraCommLinks.setText("Add Extra Comm Links");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_cbCreateMsgEvt)
                    .addComponent(f_cbAddExtraCommLinks))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f_cbCreateMsgEvt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_cbAddExtraCommLinks)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        f_bOK.setText("OK");
        f_bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_bOKActionPerformed(evt);
            }
        });

        f_bCancel.setText("Cancel");
        f_bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_bCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(f_bCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                        .addComponent(f_bOK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(f_bOK)
                    .addComponent(f_bCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
	 * @param evt  
	 */
    private void f_bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_bOKActionPerformed
    	f_config.setProperty(Constants.CONF_GENERATE_BB_POOLS, f_cbGenBBPools.isSelected() ? "1" : "0");
    	f_config.setProperty(Constants.CONF_GENERATE_DATA_OBJECTS, f_cbGenDO.isSelected() ? "1" : "0");
    	f_config.setProperty(Constants.CONF_GENERATE_ADD_UNKNOWN_PT, f_cbAddUnknown.isSelected() ? "1" : "0");
    	f_config.setProperty(Constants.CONF_GENERATE_REMOVE_LOW_ENT_NODES, f_cbRemLowEnt.isSelected() ? "1" : "0");
    	f_config.setProperty(Constants.CONF_GENERATE_HIGHLIGHT_META_ACTIONS, f_cbHighlightMeta.isSelected() ? "1" : "0");
    	f_config.setProperty(Constants.CONF_LANESO_ALWAYS_CREATE_MSG_EVT, f_cbCreateMsgEvt.isSelected() ? "1" : "0");
    	f_config.setProperty(Constants.CONF_LANESO_CREATE_EXTRA_COMM_LINKS, f_cbAddExtraCommLinks.isSelected() ? "1" : "0");
        f_config.setProperty(Constants.CONF_GENERATE_IGNORE_SBAR_ON_NP, f_cbIgnoreRelativeNPs.isSelected() ?"1":"0");
        this.setVisible(false);    	
    }//GEN-LAST:event_f_bOKActionPerformed

    /**
	 * @param evt  
	 */
    private void f_bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_bCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_f_bCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PreferencesGUI dialog = new PreferencesGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton f_bCancel;
    private javax.swing.JButton f_bOK;
    private javax.swing.JCheckBox f_cbAddExtraCommLinks;
    private javax.swing.JCheckBox f_cbAddUnknown;
    private javax.swing.JCheckBox f_cbCreateMsgEvt;
    private javax.swing.JCheckBox f_cbGenBBPools;
    private javax.swing.JCheckBox f_cbGenDO;
    private javax.swing.JCheckBox f_cbHighlightMeta;
    private javax.swing.JCheckBox f_cbIgnoreRelativeNPs;
    private javax.swing.JCheckBox f_cbRemLowEnt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void setPreferences() {
        f_cbGenBBPools.setSelected("1".equals(f_config.getProperty(Constants.CONF_GENERATE_BB_POOLS)));
        f_cbGenDO.setSelected("1".equals(f_config.getProperty(Constants.CONF_GENERATE_DATA_OBJECTS)));
        f_cbAddUnknown.setSelected("1".equals(f_config.getProperty(Constants.CONF_GENERATE_ADD_UNKNOWN_PT)));
        f_cbRemLowEnt.setSelected("1".equals(f_config.getProperty(Constants.CONF_GENERATE_REMOVE_LOW_ENT_NODES)));
        f_cbHighlightMeta.setSelected("1".equals(f_config.getProperty(Constants.CONF_GENERATE_HIGHLIGHT_META_ACTIONS)));
        f_cbCreateMsgEvt.setSelected("1".equals(f_config.getProperty(Constants.CONF_LANESO_ALWAYS_CREATE_MSG_EVT)));
        f_cbAddExtraCommLinks.setSelected("1".equals(f_config.getProperty(Constants.CONF_LANESO_CREATE_EXTRA_COMM_LINKS)));
        f_cbIgnoreRelativeNPs.setSelected("1".equals(f_config.getProperty(Constants.CONF_GENERATE_IGNORE_SBAR_ON_NP)));
    }

}
